### ISSUE TITLE
NBT outa date

### ISSUE THREAD

**Issue by 0MrCrazy0** [christopherwalkerml/DeepStoragePlus#12]
[00:55:57 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R1! Trying to find NMS support
[00:55:57 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_19_R1) is not supported by this NBT-API Version(2.9.2) located at me.darkolythe.multitool.utils.MinecraftVersion. The NBT-API will try to work as good as it can! Some functions may not work!
[00:55:57 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[00:55:57 ERROR]: Could not pass event InventoryOpenEvent to DeepStoragePlus v1.11.2
me.darkolythe.multitool.NbtApiException: [?]Error while calling the method 'getString(java.lang.String)', loaded: true, Enum: COMPOUND_GET_STRING Passed Class: class java.lang.Boolean
        at me.darkolythe.multitool.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.multitool.NBTReflectionUtil.getData(NBTReflectionUtil.java:631) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.multitool.NBTCompound.getString(NBTCompound.java:117) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.deepstorageplus.dsu.managers.SettingsManager.getOwner(SettingsManager.java:183) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.deepstorageplus.dsu.managers.SettingsManager.getLocked(SettingsManager.java:240) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.deepstorageplus.dsu.listeners.InventoryListener.onStorageOpen(InventoryListener.java:45) ~[DeepStoragePlus-1.11.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-18]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1355) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1513) ~[?:?]
        at net.minecraft.world.level.block.ChestBlock.use(ChestBlock.java:269) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1052) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-18]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@239a5368
        at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.darkolythe.multitool.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[DeepStoragePlus-1.11.2.jar:?]
        ... 31 more
[00:55:57 ERROR]: Could not pass event InventoryOpenEvent to DeepStoragePlus v1.11.2
me.darkolythe.multitool.NbtApiException: [?]Error while calling the method 'getString(java.lang.String)', loaded: true, Enum: COMPOUND_GET_STRING Passed Class: class java.lang.Boolean
        at me.darkolythe.multitool.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.multitool.NBTReflectionUtil.getData(NBTReflectionUtil.java:631) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.multitool.NBTCompound.getString(NBTCompound.java:117) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.deepstorageplus.dsu.managers.SettingsManager.getOwner(SettingsManager.java:183) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.deepstorageplus.dsu.managers.SettingsManager.getLocked(SettingsManager.java:240) ~[DeepStoragePlus-1.11.2.jar:?]
        at me.darkolythe.deepstorageplus.dsu.listeners.InventoryListener.onStorageOpen(InventoryListener.java:45) ~[DeepStoragePlus-1.11.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-18]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1355) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.level.ServerPlayer.openMenu(ServerPlayer.java:1513) ~[?:?]
        at net.minecraft.world.level.block.ChestBlock.use(ChestBlock.java:269) ~[?:?]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.use(BlockBehaviour.java:1052) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:571) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-18]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-18]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@3029e120
        at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.darkolythe.multitool.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[DeepStoragePlus-1.11.2.jar:?]
        ... 31 more
[00:55:57 WARN]: [NBTAPI] [NBTAPI] The NBT-API located at 'package me.darkolythe.multitool' seems to be outdated!
[00:55:57 WARN]: [NBTAPI] [NBTAPI] Current Version: '2.9.2' Newest Version: 2.10.0'
[00:55:57 WARN]: [NBTAPI] [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!

**Comment by FamousL** [comment]
WARNING: Not a maintainer, this could introduce errors that I don't see right now!!!!!!


Ok, for anyone willing to get their hands dirty, here is a workaround that seems to work for my server:


- clone repo, and the repo at https://github.com/christopherwalkerml/CustomRecipeAPI
- modify pom.xml to change the output directory of org.apache.maven.plugins to something that exists on your machine (ex target/)
- compile using maven, copy jar to DeepStoragePlus's repo clone (remember where you put it, you will need this)
- Update pom.xml for DeepStoragePlus to include the following:
-        CustomRecipeAPI has a hard link to the original creator's disk, change this to the fresh compile of CustomRecipeAPI
-        Modify output directory of org.apache.maven.plugins to something that exists on your machine (ex target)
-        Modify de.tr7zw dependency to version 2.10.0
- use maven to compile DeepStoragePlus
- move fresh compile (remember you told it where to place it) to your server
- reboot (don't reload) your server

**Comment by wpmidia** [comment]
The same problem here!

```
[13:09:10 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_19_R2! Trying to find NMS support
[13:09:10 WARN]: [NBTAPI] [NBTAPI] This Server-Version(v1_19_R2) is not supported by this NBT-API Version(2.10.0) located at me.darkolythe.deepstorageplus.utils.MinecraftVersion. The NBT-API will try to work as good as it can! Some functions may not work!
[13:09:10 INFO]: [NBTAPI] [NBTAPI] Found Gson: class com.google.gson.Gson
[13:09:11 WARN]: [NBTAPI] [NBTAPI] The NBT-API located at 'package me.darkolythe.deepstorageplus' seems to be outdated!
[13:09:11 WARN]: [NBTAPI] [NBTAPI] Current Version: '2.10.0' Newest Version: 2.11.2'
[13:09:11 WARN]: [NBTAPI] [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!
```
